/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMenuCourse: typeof import('./src/components/AddMenuCourse.vue')['default']
    AddStudentMenu: typeof import('./src/components/AddStudentMenu.vue')['default']
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    CourseSortMenu: typeof import('./src/components/CourseSortMenu.vue')['default']
    CourseToggleMenu: typeof import('./src/components/CourseToggleMenu.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EditLessonMenu: typeof import('./src/components/EditLessonMenu.vue')['default']
    EditStudenttoggleMenu: typeof import('./src/components/EditStudenttoggleMenu.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    N: typeof import('./src/components/N.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Password: typeof import('primevue/password')['default']
    ProductOverviewWidget: typeof import('./src/components/dashboard/ProductOverviewWidget.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RecentActivityWidget: typeof import('./src/components/dashboard/RecentActivityWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendWidget: typeof import('./src/components/dashboard/SalesTrendWidget.vue')['default']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    SortMenu: typeof import('./src/components/SortMenu.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    StudentMenuall: typeof import('./src/components/StudentMenuall.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleMenu: typeof import('./src/components/ToggleMenu.vue')['default']
    UpdateCourseMenu: typeof import('./src/components/UpdateCourseMenu.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
